# Generated by Django 3.1.4 on 2021-05-20 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project',
            new_name='project_title',
        ),
    ]
