# Generated by Django 3.1.4 on 2021-05-20 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_auto_20210520_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='tasks',
            new_name='task_name',
        ),
    ]
