# Generated by Django 3.1.3 on 2021-05-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_auto_20210520_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='from_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='to_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
