# Generated by Django 3.0.6 on 2020-10-20 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_last_name', models.CharField(max_length=30)),
                ('emp_gender', models.CharField(max_length=30)),
                ('emp_dob', models.DateField()),
                ('emp_education', models.CharField(max_length=30)),
                ('emp_email', models.CharField(max_length=30)),
                ('emp_field', models.CharField(max_length=30)),
                ('emp_payment', models.CharField(max_length=30)),
                ('emp_phone', models.CharField(max_length=30)),
                ('emp_address', models.CharField(max_length=30)),
                ('emp_name', models.CharField(max_length=30)),
                ('emp_photo', models.ImageField(upload_to='employee_photoes')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('pay_to', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('Phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('describe_payment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=30)),
                ('explain_field', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=300)),
                ('posted_by', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pay_slip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Attendance', models.CharField(max_length=30)),
                ('emp_iid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Employee')),
            ],
        ),
    ]
