# Generated by Django 3.0.6 on 2020-10-20 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20201020_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='Attendance',
            new_name='presenty',
        ),
    ]
