# Generated by Django 3.0.6 on 2020-10-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20201020_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='emp_iid',
            field=models.CharField(max_length=30),
        ),
    ]
