# Generated by Django 3.0.6 on 2020-10-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_auto_20201020_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay_slip',
            name='email',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='pay_slip',
            name='emp_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pay_slip',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pay_slip',
            name='amount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pay_slip',
            name='emp_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pay_slip',
            name='pay_date',
            field=models.DateField(blank=True),
        ),
    ]
