# Generated by Django 3.1.4 on 2021-06-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_auto_20210520_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_slip',
            name='pay_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
